### PR TITLE
Fixup RST styling in acle.rst.

### PR DESCRIPTION
**Pull request by georges-arm**
Just a few minor fixes for RST styling in acle.rst, plus trimming some trailing whitespace.

### CODE REVIEW

**Review by fpetrogalli — COMMENTED** [review]
@georges-arm , thank you for your patch.

I feel that your changes are not trivial from a typographical point of view, do you mind updating the changes for next release section with a description of what you have changed? Something along the lines of "fixed item lists rendering in sections A and B"

https://github.com/ARM-software/acle/blob/next-release/main/acle.rst#changes-for-next-release

Francesco

**Comment by georges-arm** [comment]
Hi @fpetrogalli.

Thanks for the review, I have added a couple of changelog entries but wasn't sure how specific you wanted me to be. I can add more specific section references if you'd prefer, but that would lead to a lot of changelog entries?

Thanks,
George

**Review by fpetrogalli — APPROVED** [review]
Thank you @georges-arm, this LGTM.

Are you happy for me to add you in the list of contributors in https://github.com/ARM-software/acle#contributors-

Francesco

**Comment by georges-arm** [comment]
That's fine. Do you want me to do that myself in a new PR or do you want to do it yourself?

**Comment by fpetrogalli** [comment]
No worries @georges-arm , we have someone taking care of updating the contributors list for us. @allcontributors please add @georges-arm for code. :)

**Comment by fpetrogalli** [comment]
Thank you @allcontributors! Very kind of you.

**Pull request merged**
